/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package APP;

import MEMBER1.SummaryUI;
import MEMBER1.LogMealUI;
import APP.HomePageUI;
import MEMBER1.LogExerciseUI;
import MEMBER1.LogExerciseUI;

/**
 *
 * @author Alexb
 */
public class HealthFitnessUI extends javax.swing.JPanel {

    /**
     * Creates new form HealthFitnessUI
     */
    public HealthFitnessUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogMeal = new javax.swing.JButton();
        btnLogExercise = new javax.swing.JButton();
        btnSummary = new javax.swing.JButton();
        btnHomePage = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        btnLogMeal.setText("Log Meals");
        btnLogMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogMealActionPerformed(evt);
            }
        });

        btnLogExercise.setText("Log Excersise");
        btnLogExercise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogExerciseActionPerformed(evt);
            }
        });

        btnSummary.setText("SUMMARY");
        btnSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSummaryActionPerformed(evt);
            }
        });

        btnHomePage.setText("HOMEPAGE");
        btnHomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePageActionPerformed(evt);
            }
        });

        jLabel1.setText("FITNESS AND NUTRITION HOME");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogExercise)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnSummary, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnHomePage))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLogMeal)
                        .addGap(8, 8, 8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(btnLogMeal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogExercise)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSummary)
                .addGap(18, 18, 18)
                .addComponent(btnHomePage)
                .addContainerGap(87, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePageActionPerformed
           Screen.show(new HomePageUI(), "Home");
    }//GEN-LAST:event_btnHomePageActionPerformed

    private void btnLogMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogMealActionPerformed
        Screen.show(new LogMealUI(), "Log Meal");
    }//GEN-LAST:event_btnLogMealActionPerformed

    private void btnLogExerciseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogExerciseActionPerformed
            Screen.show(new LogExerciseUI(), "Log Exercise");
    }//GEN-LAST:event_btnLogExerciseActionPerformed

    private void btnSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSummaryActionPerformed
        Screen.show(new SummaryUI(), "SUMMARY ");
    }//GEN-LAST:event_btnSummaryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHomePage;
    private javax.swing.JButton btnLogExercise;
    private javax.swing.JButton btnLogMeal;
    private javax.swing.JButton btnSummary;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
