package APP;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Alexb
 */
public class HomePageUI extends javax.swing.JPanel {

    /**
     * Creates new form HomePageUI
     */
    public HomePageUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        btnFintness = new javax.swing.JButton();
        btnMental = new javax.swing.JButton();
        btnCommunity = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        btnFintness.setText("Fintness & Nutrition");
        btnFintness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFintnessActionPerformed(evt);
            }
        });

        btnMental.setText("Mental Health Hub");
        btnMental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMentalActionPerformed(evt);
            }
        });

        btnCommunity.setText("Community Challenges");
        btnCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommunityActionPerformed(evt);
            }
        });

        jLabel1.setText("HOMEPAGE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCommunity)
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFintness)
                            .addComponent(btnMental))
                        .addGap(126, 126, 126))))
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addComponent(btnFintness)
                .addGap(26, 26, 26)
                .addComponent(btnMental)
                .addGap(30, 30, 30)
                .addComponent(btnCommunity)
                .addContainerGap(280, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMentalActionPerformed
        Screen.show(new MentalHubUI(), "Mental Health Hub");
    }//GEN-LAST:event_btnMentalActionPerformed

    private void btnCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommunityActionPerformed
       Screen.show(new CommunityChallengeUI(), "Community Challenges");
    }//GEN-LAST:event_btnCommunityActionPerformed

    private void btnFintnessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFintnessActionPerformed
        Screen.show(new HealthFitnessUI(), "Fitness & Nutrition");
    }//GEN-LAST:event_btnFintnessActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCommunity;
    private javax.swing.JButton btnFintness;
    private javax.swing.JButton btnMental;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
