/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package APP;

import MEMBER2.MoodTrackerUI;
import MEMBER2.MeditationTimerUI;
import MEMBER2.JournalEntryUI;

/**
 *
 * @author Alexb
 */
public class MentalHubUI extends javax.swing.JPanel {

    /**
     * Creates new form MentalHubUI
     */
    public MentalHubUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMoodTracker = new javax.swing.JButton();
        btnJournalEntries = new javax.swing.JButton();
        btnMeditationTimer = new javax.swing.JButton();
        btnHomepage = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        btnMoodTracker.setText("Mood Tracker");
        btnMoodTracker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoodTrackerActionPerformed(evt);
            }
        });

        btnJournalEntries.setText("Journal Entries");
        btnJournalEntries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJournalEntriesActionPerformed(evt);
            }
        });

        btnMeditationTimer.setText("Meditation Timer");
        btnMeditationTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeditationTimerActionPerformed(evt);
            }
        });

        btnHomepage.setText("HOMEPAGE");
        btnHomepage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomepageActionPerformed(evt);
            }
        });

        jLabel1.setText("MENTAL HUB ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(btnHomepage))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMeditationTimer)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnJournalEntries)
                                    .addComponent(btnMoodTracker))
                                .addGap(2, 2, 2)))))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(btnMoodTracker)
                .addGap(30, 30, 30)
                .addComponent(btnJournalEntries)
                .addGap(33, 33, 33)
                .addComponent(btnMeditationTimer)
                .addGap(18, 18, 18)
                .addComponent(btnHomepage)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomepageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomepageActionPerformed
      Screen.show(new HomePageUI(), "Home");
    }//GEN-LAST:event_btnHomepageActionPerformed

    private void btnMoodTrackerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoodTrackerActionPerformed
        Screen.show(new MoodTrackerUI(), "Mood Tracker");
    }//GEN-LAST:event_btnMoodTrackerActionPerformed

    private void btnJournalEntriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJournalEntriesActionPerformed
        Screen.show(new JournalEntryUI(), "Journal Entries");
    }//GEN-LAST:event_btnJournalEntriesActionPerformed

    private void btnMeditationTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeditationTimerActionPerformed
       Screen.show(new MeditationTimerUI(), "Meditation Timer");
    }//GEN-LAST:event_btnMeditationTimerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHomepage;
    private javax.swing.JButton btnJournalEntries;
    private javax.swing.JButton btnMeditationTimer;
    private javax.swing.JButton btnMoodTracker;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
