/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MEMBER3;

import APP.HomePageUI;
import APP.Screen;
import javax.swing.JOptionPane;
/**
 *
 * @author Alexb
 */
public class ChallengeListUI extends javax.swing.JPanel 
       
{  private Leaderboard leaderboard = Member3Data.leaderboard;


    /**
     * Creates new form ChallengeListUI
     */
    public ChallengeListUI() {
        initComponents();
    }
    
   
            


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Daily Step Challenge ", "30-Minute Workout Challenge", "Hydration Challenge" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        btnSave.setText("JOIN");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnBack))
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       Screen.show(new CommunityChallengeUI(), "Community Challenges");
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
                                       

      // Get the challenge the user selected from the JList
        String selected = jList1.getSelectedValue();

      // If no challenge was selected it tells user message
              if (selected == null) {
            JOptionPane.showMessageDialog(this, "Please select a challenge to join.");
            return;
           }
        
     // Variables to store the challenge goal and points
        int goal = 0;
        int points = 0;

     // Set the correct goal and points depending on the selected challenge
     switch (selected) {
            case "Daily Step Challenge ":
        goal = 10000;   // user must reach 10,000 steps
        points = 10;    // points earned
        break;

            case "30-Minute Workout Challenge":
        goal = 30;      // user must complete 30 minutes of activity
        points = 15;
        break;

            case "Hydration Challenge":
        goal = 20;      // user must drink 20 litres of water total
        points = 5;
        break;
        }

        // default user
        String username = "User1";

        // Gets user's progress profile from the Leaderboard
        UserProgress user = leaderboard.findUser(username);
        //if the user dosent exists creates new user
            if (user == null) {
            user = new UserProgress(username);
        }

        // makes a new challenge with, challenge name,string, points etc
        ChallengeEntry entry = new ChallengeEntry(selected, "", points, goal, false);


          //adds challenege to users active challenege list
            user.addActiveChallenge(entry);

          // Update leaderboard with the user and their new active challenge
            leaderboard.addOrUpdateUser(user);

          // Display confirmation message to the user
                JOptionPane.showMessageDialog(this,
                 "You joined: " + selected +
                    "\nGoal: " + goal +
                        "\nNow update your progress in the Progress screen!");

    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}