/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MEMBER3;




import MEMBER3.Screen;
import MEMBER3.LeaderboardUI;
import MEMBER3.ChallengeProgressUI;
import MEMBER3.ChallengeListUI;
import MEMBER3.ChallengeListUI;
import MEMBER3.ChallengeProgressUI;
import MEMBER3.LeaderboardUI;

/**
 *
 * @author Alexb
 */
public class CommunityChallengeUI extends javax.swing.JPanel {

    /**
     * Creates new form CommunityChallengeUI
     */
    public CommunityChallengeUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnChallengerList = new javax.swing.JButton();
        btnCommunity2 = new javax.swing.JButton();
        btnCommunity3 = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        btnChallengerList.setText("ChallengerList");
        btnChallengerList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChallengerListActionPerformed(evt);
            }
        });

        btnCommunity2.setText("ChallengeProgress");
        btnCommunity2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommunity2ActionPerformed(evt);
            }
        });

        btnCommunity3.setText("LeaderBoard");
        btnCommunity3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommunity3ActionPerformed(evt);
            }
        });

        btnHome.setText("HOMEPAGE");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        jLabel1.setText("COMMUNITY CHALLENGE HOME");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnChallengerList)
                        .addGap(133, 133, 133))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCommunity2)
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(110, 110, 110))))
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnHome)
                    .addComponent(btnCommunity3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(btnChallengerList)
                .addGap(18, 18, 18)
                .addComponent(btnCommunity2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnCommunity3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(btnHome)
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCommunity2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommunity2ActionPerformed
          Screen.show(new ChallengeProgressUI(), "Challenge Progress");
    }//GEN-LAST:event_btnCommunity2ActionPerformed

    private void btnCommunity3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommunity3ActionPerformed
         Screen.show(new LeaderboardUI(), "Leaderbaord");
    }//GEN-LAST:event_btnCommunity3ActionPerformed

    private void btnChallengerListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChallengerListActionPerformed
          Screen.show(new ChallengeListUI(), "Challenge List");
    }//GEN-LAST:event_btnChallengerListActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
     
      
    }//GEN-LAST:event_btnHomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChallengerList;
    private javax.swing.JButton btnCommunity2;
    private javax.swing.JButton btnCommunity3;
    private javax.swing.JButton btnHome;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
